# Generated by Django 5.1.2 on 2024-10-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
